Savoy/Savoy/Controllers/ShopController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Savoy.Areas.Admin.ViewModels.ProductVM;
using Savoy.Data;
using Savoy.Helpers;
using Savoy.Models;
using Savoy.Service;
using Savoy.Service.Interfaces;
using Savoy.ViewModels;
using System.Collections.Immutable;

namespace Savoy.Controllers
{
    public class ShopController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IColorService _colorService;
        private readonly ITagService _tagService;
        private readonly ICategoryService _categoryService;
        private readonly IProductService _productService;
        private readonly UserManager<AppUser> _userManager;

        public ShopController(AppDbContext context,
                              IColorService colorService,
                              ITagService tagService,
                              ICategoryService categoryService,
                              IProductService productService,
                              UserManager<AppUser> userManager)
        {
            _context = context;
            _colorService = colorService;
            _tagService = tagService;
            _categoryService = categoryService;
            _productService = productService;
            _userManager = userManager;
        }


        public async Task<IActionResult> Index(int? categoryId = null, int? tagId = null, int? colorId = null, int page = 1, int take = 8, string searchText = null)
        {

            IEnumerable<Color> colors = await _colorService.GetAllAsync();
            IEnumerable<Tag> tags = await _tagService.GetAllAsync();
            IEnumerable<Category> categories = await _categoryService.GetAllAsync();

            IEnumerable<Product> products = await _productService.GetPaginationData(categoryId, tagId, colorId, page, take, searchText);

            List<ShopVM> mappedDatas = GetMappedDatas(products, tags, colors, categories);

            int pageCount = await GetPageCountAsync(take, categoryId, searchText, tagId, colorId);

            Paginate<ShopVM> paginatedDatas = new(mappedDatas, page, pageCount);

            ViewBag.take = take;

            //ViewBag.searchText = searchText;


            return View(paginatedDatas);
        }

        private async Task<int> GetPageCountAsync(int take, int? categoryId, string searchText, int? tagId, int? colorId)
        {

            if (categoryId == null)
            {
                if (searchText != null)
                {

                    if (tagId != null && colorId != null)
                    {
                        int productSearchTextTagColor = await _context.Products.Where(m => !m.SoftDelete && m.Name.ToLower().
                                                                                  Trim().Contains(searchText.ToLower().Trim())).Include(m => m.ProductImages).Include(m => m.ProductCategories).
                                                                                  ThenInclude(m => m.Category).
                                                                                  Where(x => x.ProductColors.Any(xt => xt.ColorId == colorId)).
                                                                                  Where(x => x.ProductTags.Any(xt => xt.TagId == tagId)).
                                                                                  CountAsync();

                        ViewBag.tagId = tagId;
                        ViewBag.colorId = colorId;
                        ViewBag.searchText = searchText;
                        return (int)Math.Ceiling((decimal)productSearchTextTagColor / take);
                    }
                    if (colorId != null && tagId == null)
                    {
                        int productSearchTextColor = await _context.Products.Include(m => m.ProductImages).Include(m => m.ProductCategories).
                                                                                     ThenInclude(m => m.Category).
                                                                                     Where(x => x.ProductColors.Any(xt => xt.ColorId == colorId)).
                                                                                     Where(m => !m.SoftDelete && m.Name.ToLower().
                                                                                     Trim().Contains(searchText.ToLower().Trim())).
                                                                                     CountAsync();


                        ViewBag.tagId = null;
                        ViewBag.colorId = colorId;
                        ViewBag.searchText = searchText;
                        return (int)Math.Ceiling((decimal)productSearchTextColor / take);
                    }
                    if (colorId == null && tagId != null)
                    {
                        int productSearchTextTag = await _context.Products.Include(m => m.ProductImages).Include(m => m.ProductCategories).
                                                                                     ThenInclude(m => m.Category).
                                                                                     Where(x => x.ProductTags.Any(xt => xt.TagId == tagId)).
                                                                                     Where(m => !m.SoftDelete && m.Name.ToLower().
                                                                                     Trim().Contains(searchText.ToLower().Trim())).
                                                                                     CountAsync();

                        ViewBag.tagId = tagId;
                        ViewBag.colorId = null;
                        ViewBag.searchText = searchText;
                        return (int)Math.Ceiling((decimal)productSearchTextTag / take);

                    }




                    int productSearchTextCount = await _context.Products.Include(m => m.ProductImages).
                                                   Include(m => m.ProductCategories).
                                                   OrderByDescending(m => m.Id).
                                                   Where(m => !m.SoftDelete && m.Name.ToLower().
                                                   Trim().Contains(searchText.ToLower().Trim()))
                                                   .CountAsync();


                    ViewBag.tagId = null;
                    ViewBag.colorId = null;
                    ViewBag.searchText = searchText;

                    return (int)Math.Ceiling((decimal)productSearchTextCount / take);
                }

                if (tagId != null && colorId != null)
                {
                    int sortProductTagColor = await _context.Products.Include(m => m.ProductImages).Include(m => m.ProductCategories).
                                                                                     ThenInclude(m => m.Category).
                                                                                     Where(x => x.ProductColors.Any(xt => xt.ColorId == colorId)).
                                                                                     Where(x => x.ProductTags.Any(xt => xt.TagId == tagId)).
                                                                                     CountAsync();
                    ViewBag.searchText = null;
                    ViewBag.tagId = tagId;
                    ViewBag.colorId = colorId;
                    return (int)Math.Ceiling((decimal)sortProductTagColor / take);

                }

                if (tagId != null && colorId == null)
                {
                    int sortProductTag = await _context.Products.Include(m => m.ProductImages).Include(m => m.ProductCategories).
                                                                                      ThenInclude(m => m.Category).
                                                                                      Where(x => x.ProductTags.Any(xt => xt.TagId == tagId)).
                                                                                      CountAsync();
                    ViewBag.searchText = null;
                    ViewBag.tagId = tagId;
                    ViewBag.colorId = null;
                    return (int)Math.Ceiling((decimal)sortProductTag / take);
                }

                if (tagId == null && colorId != null)
                {
                    int sortProductColor = await _context.Products.Include(m => m.ProductImages).Include(m => m.ProductCategories).
                                                                                      ThenInclude(m => m.Category).
                                                                                      Where(x => x.ProductColors.Any(xt => xt.ColorId == colorId)).
                                                                                      CountAsync();
                    ViewBag.searchText = null;
                    ViewBag.tagId = null;
                    ViewBag.colorId = colorId;
                    return (int)Math.Ceiling((decimal)sortProductColor / take);

                }



                int producttCount = await _productService.GetCountAsync();
                ViewBag.categoryId = null;
                ViewBag.searchText = null;
                ViewBag.colorId = null;
                ViewBag.tagId = null;
                return (int)Math.Ceiling((decimal)producttCount / take);
            }

            if (searchText != null)
            {


                if (colorId != null && tagId != null)
                {
                    int productCategorySearchTextColorTag = await _context.Products.Where(x => x.ProductCategories.Any(xt => xt.CategoryId == categoryId)).

Savoy/Savoy/Views/Shop/Detail.cshtml
@model ShopDetailVM

@{
    ViewData["Title"] = "Shop Detail";
}

@section Style{

    <link rel="stylesheet" href="~/assets/scss/pages/shopdetailpage/shopdetailpage.css" />
}

<main>

    <section id="carouselshop">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6 col-md-12 col-sm-12">
                    <div class="pagecategory">
                        <ul>
                            <li>Shop</li>
                            <li>/</li>
                            @foreach (var category in Model.ProductCategories)
                            {
                                <li>@category</li>
                            }
                            <li>/</li>
                            <li>@Model.Name</li>
                        </ul>
                    </div>
                    <div id="carouselExampleFade" class="carousel slide carousel-fade">
                        <div class="carousel-inner">

                            <div class="carousel-item active">
                                <img src="~/assets/image/@Model.ProductImages.FirstOrDefault()" class="d-block w-100" alt="...">
                            </div>

                            @if(Model.ProductImages.Skip(1).FirstOrDefault() != null){
                                @foreach (var image in Model.ProductImages.Skip(1))
                                {
                                    <div class="carousel-item">
                                        <img src="~/assets/image/@image" class="d-block w-100" alt="...">
                                    </div>
                                }
                            }
                            else
                            {
                                 <div class="carousel-item">
                                        <img src="~/assets/image/@Model.ProductImages.FirstOrDefault()" class="d-block w-100" alt="...">
                                    </div>
                            }


                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade"
                                data-bs-slide="prev">
                            <span class="carousel-control-prev-icon lefticon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade"
                                data-bs-slide="next">
                            <span class="carousel-control-next-icon"></span>
                            <span style="color:black !important" aria-hidden="true"
                                  class="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>

                <div class="col-lg-6 col-md-6 col-sm-12">
                    <div class="productinfos">
                        <h3>@Model.Name</h3>
                        <span>$</span><span>@Model.Price</span>
                        <p>
                            Designed for simplicity and made from high quality materials. Its sleek geometry and
                            material combinations creates a modern personalized look.
                        </p>
                        <div class="rating">
                          
                           @for (int i = 0; i < Model.RatesWorth / Model.RatesCount; i++)
                            {
                                <i class="fa-regular fa-star"></i>
                            }

                        </div>
                       @* <select name="colorId" id="">
                            <option selected default value="">@Model.ProductColors.FirstOrDefault()</option>
                           @foreach (var color in Model.ProductColors.Skip(1))
                            {
                                <option value="">@color</option>
                            }
                        </select>*@
                        <form asp-controller="Shop"asp-action="AddBasket" asp-route-id="@Model.Id">
                        <div class="quantity">


                            <ul>
                                <span class="countproduct">Quantity</span>
                                <li>
                                    <i class="fa-solid fa-minus"></i>
                                </li>
                                <li>
                                        <input style="background:#f0eded" name="quantity" min="1" value="1" type="number" readonly>
                                </li>
                                <li>
                                    <i class="fa-solid fa-plus"></i>
                                </li>
                            </ul>

                        </div>

                   
                            <button type="submit">Add to cart</button>
                        </form>

                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="productdetail">
                    <div class="headers">
                        <ul>
                            <li data-id="1" class="active">Description</li>
                            <li data-id="2">Additional information</li>
                            <li data-id="3">Comments</li>
                        </ul>
                    </div>
                    <div class="content">
                        <div data-id="1" class="descriptioninfo">
                            <p>
                              @Model.Description
                            </p>
                        </div>

                        <div data-id="2" class="additionalinfo d-none">

                            <table>
                                <thead>
                                    <tr>
                                        <td>Weight</td>
                                        <td>@Model.Weight</td>
                                    </tr>
                                    <tr>
                                        <td>Dimensions</td>
                                        <td>@Model.Dimensions</td>
                                    </tr>
                                    <tr>
                                        <td>Materials</td>
                                        <td>@Model.Materials</td>
                                    </tr>
                                    <tr>
                                        <td>Other Info</td>
                                        <td>@Model.OtherInfo</td>
                                    </tr>
                                </thead>
                            </table>
                        </div>

                        <div data-id="3" class="comments d-none">


                            <div class="comment" >
                                <h2>UserName</h2>
                                <p>Loremdscvnskjdncvdsncvoajsdfnovjadsfnv;ajdfsnv;ufdohnv;osudifhg; hgpuiosrghpklvnmdsaikvnaosinvh</p>
                            </div>

                        
                            <form asp-controller="Shop" asp-action="AddComment" asp-route-userId="" asp-route-productId="@Model.Id">

                                <input type="text" />

                                <button type="submit">Add comment</button>
                            </form>
                        
                              
                           
                        </div>
                    </div>
                </div>
                <div class="tag">
                    <ul>
                        <li>SKU: <span> @Model.Sku</span></li>
                        <li>Category:
                            @foreach (var category in Model.ProductCategories)
                            {
                                <span>@category</span>
                            }
                        </li>
                        <li>Tags: @foreach (var tag in Model.ProductTags)
                            {
                                <span>@tag</span>

                            }
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

</main>

@section Script{

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/js/shopdetail.js"></script>

}

Savoy/Savoy/Views/Shop/Index.cshtml
@using Savoy.Helpers;
@model Paginate<ShopVM>

@{
    ViewData["Title"] = "Shop";
    //Viewbag.categoryId = @Model.Datas.FirstOrDefault().Products.FirstOrDefault().ProductCategories.FirstOrDefault().CategoryId;


}

@section Style{

    <link rel="stylesheet" href="~/assets/scss/pages/shoppage/shoppage.css" />

}

<main>

    <!-- Categories/Search/Filter/Sorted -->
    <section id="categories-search-filter">
        <div class="container-fluid my-3">
            <div class="row">
                <div class="col-lg-9">
                    <div class="categoriesname">
                        <ul>
                            <a data-id="All" asp-action="Index" class="active allCategoriesName categoriesName">All<span>/</span></a>

                            @foreach (var category in Model.Datas.FirstOrDefault().Categories)
                            {
                                <a class="categoriesName" data-id="@category.Id" asp-action="Index" asp-route-categoryId="@category.Id">@category.Name<span>/</span></a>
                            }

                        </ul>
                    </div>
                </div>

                <div class="col-lg-3">
                    <div class="filtersort">
                        <ul>
                            <li>Filter<span>/</span></li>
                            <li>Search <i class="fa-solid fa-magnifying-glass"></i></li>
                        </ul>
                    </div>

                </div>
            </div>

            <div class="col-lg-12">
                <div class="searcharea d-none">
                    <form asp-controller="Shop" asp-action="Index" asp-route-categoryId="@ViewBag.categoryId" asp-route-tagId="@ViewBag.tagId" asp-route-colorId="@ViewBag.colorId">
                        <input name="searchText" class="hm-searchbox" placeholder="Search products" type="text"><button type="submit">Search</button>  <i class="fa-solid fa-xmark"></i>
                    </form>

                </div>

                <div class="filter d-none">
                    <div class="col-lg-3">
                        <h5>Sort By</h5>
                        <ul>
                            <li>Default</li>
                            <li>Popularity</li>
                            <li>Average rating</li>
                            <li>Newness</li>
                            <li>Price: Low to High</li>
                            <li>Price: High to Low</li>
                        </ul>
                    </div>
                    <div class="col-lg-3">
                        <h5>Price</h5>
                        <ul>
                            <li>All</li>
                            <li>$0 - $50</li>
                            <li>$50 - $100</li>
                            <li>$100 - $150</li>
                            <li>$150 - $200</li>
                            <li>$200+</li>
                        </ul>
                    </div>
                    <div class="col-lg-3">
                        <h5>Color</h5>
                        <ul class="color">

                            @foreach (var color in Model.Datas.FirstOrDefault().Colors)
                            {
                                <li><i class="fa-solid fa-circle"></i><a asp-controller="Shop" asp-action="Index" asp-route-categoryId="@ViewBag.categoryId" asp-route-tagId="@ViewBag.tagId" asp-route-searchText="@ViewBag.searchText" asp-route-colorId="@color.Id">@color.Name</a></li>
                            }

                        </ul>
                    </div>
                    <div class="col-lg-3">
                        <div class="tags">
                            <h5>Tags</h5>

                            @foreach (var tag in Model.Datas.FirstOrDefault().Tags)
                            {
                                <a asp-controller="Shop" asp-action="Index" asp-route-categoryId="@ViewBag.categoryId" asp-route-colorId="@ViewBag.colorId" asp-route-searchText="@ViewBag.searchText" asp-route-tagId="@tag.Id">@tag.Name</a>
                            }

                        </div>
                    </div>
                </div>

                <div class="content">
                  

                    <div class="item">

                        @if (Model.Datas.FirstOrDefault().Products.Count() == 0)
                        {
                            <div class="alert alert-danger" style="text-align:center;width:100%;" role="alert">
                                Product not found!
                            </div>
                        }
                        else
                        {
                            @foreach (var product in Model.Datas.FirstOrDefault().Products)
                            {
                                <div class="col-lg-3">


                                    <div class="productcart">

                                        <img class="firstimg" src="~/assets/image/@product.ProductImages.Where(m=>m.IsMain).FirstOrDefault()?.Image" alt="">
                                        <a asp-controller="shop" asp-action="Detail" asp-route-id="@product.Id">
                                            @if (product.ProductImages.Where(m => m.HoverImage).FirstOrDefault().Image == null)
                                            {
                                                <img class="secondimg"
                                         src="~/assets/image/@product.ProductImages.Where(m=>m.IsMain).FirstOrDefault()?.Image" alt="">
                                            }
                                            else
                                            {
                                                <img class="secondimg"
                                         src="~/assets/image/@product.ProductImages.Where(m=>m.HoverImage).FirstOrDefault()?.Image" alt="">
                                            }
                                        </a>
                                        <div class="productinfo">
                                            <span>@product.Name</span><a style="float:right;" asp-controller="Shop" asp-action="AddWishlist" asp-route-productId="@product.Id">
                                                <i class="fa-regular fa-heart like"></i>
                                            </a>
                                            <div class="pricelike" style="margin-top:13px;">
                                                <span class="pricecurrency">$<span>@product.Price</span></span>

                                                <form style="display:inline-block;position:absolute;right:8px;" asp-controller="Shop" asp-action="AddBasket" asp-route-Id="@product.Id" asp-route-quantity="1">
                                                    <button style="border:none;background-color:white;padding-left:100px;" type="submit" class="showmore"><i style="color:#282828;font-size:22px;" class="fa-solid fa-cart-shopping"></i></button>
                                                </form>


                                            </div>





                                            @* <div class="rating">
                                    @for (int i = 0; i < product.RatesWorth / product.RatesCount; i++)
                                    {
                                    <i class="fa-solid fa-star"></i>
                                    }


                                    </div>*@
                                        </div>
                                    </div>


                                
                                </div>
                            }
                        }



                    </div>

                </div>
            </div>



            @if (Model.Datas.FirstOrDefault().Products.Count() > 0)
            {
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item @(Model.HasPrevious? "":"disabled")">

                            <a class="page-link" asp-action="Index" asp-route-searchText="@ViewBag.searchText" asp-route-categoryId="@ViewBag.categoryId" asp-route-tagId="@ViewBag.tagId" asp-route-colorId="@ViewBag.colorId" asp-route-page="@(Model.CurrentPage - 1)" tabindex="-1">Previous</a>
                        </li>

                        @for (int i = 1; i <= Model.TotalPages; i++)
                        {
                            <li class=" page-item @(Model.CurrentPage == i ? "disabled":"")">
                                <a class="page-link page" asp-action="Index" asp-route-searchText="@ViewBag.searchText" asp-route-categoryId="@ViewBag.categoryId" asp-route-tagId="@ViewBag.tagId" asp-route-colorId="@ViewBag.colorId" asp-route-page="@i">@i</a>

                            </li>

                        }

                        <li class="page-item @(Model.HasNext? "":"disabled")">
                            <a class="page-link" asp-action="Index" asp-route-searchText="@ViewBag.searchText" asp-route-categoryId="@ViewBag.categoryId" asp-route-tagId="@ViewBag.tagId" asp-route-colorId="@ViewBag.colorId" asp-route-page="@(Model.CurrentPage + 1)">Next</a>
                        </li>
                    </ul>
                </nav>
            }


        </div>
    </section>

    <section id="carousel">

        <div class="container-fluid">

            @if (Model.Datas.FirstOrDefault().Products.Count() > 0)
            {

                <h2 style="margin-top:50px;margin-bottom:40px;">Relations Products</h2>
                <swiper-container class="mySwiper" space-between="25" slides-per-view="auto" pagination="true"
                              pagination-clickable="true">



                    @foreach (var product in Model.Datas.FirstOrDefault().Products.OrderByDescending(m => m.Created).Take(10))
                    {
                        <swiper-slide>
                            <div class="productcart">

                                <img class="firstimg" src="~/assets/image/@product.ProductImages.Where(m=>m.IsMain).FirstOrDefault()?.Image" alt="">
                                <a asp-controller="shop" asp-action="Detail" asp-route-id="@product.Id">
                                    @if (product.ProductImages.Where(m => m.HoverImage).FirstOrDefault().Image == null)
                                    {
                                        <img class="secondimg"
                                 src="~/assets/image/@product.ProductImages.Where(m=>m.IsMain).FirstOrDefault()?.Image" alt="">
                                    }
                                    else
                                    {
                                        <img class="secondimg"
                                 src="~/assets/image/@product.ProductImages.Where(m=>m.HoverImage).FirstOrDefault()?.Image" alt="">
                                    }
                                </a>
                                <div class="productinfo">
                                    <span>@product.Name</span><a style="float:right;" asp-controller="Shop" asp-action="AddWishlist" asp-route-productId="@product.Id">
                                        <i class="fa-regular fa-heart like"></i>
                                    </a>
                                    <div class="pricelike" style="margin-top:13px;">
                                        <span class="pricecurrency">$<span>@product.Price</span></span>

                                        <form style="display:inline-block;position:absolute;right:8px;" asp-controller="Shop" asp-action="AddBasket" asp-route-Id="@product.Id" asp-route-quantity="1">
                                            <button style="border:none;background-color:white;padding-left:100px;" type="submit" class="showmore"><i style="color:#282828;font-size:22px;" class="fa-solid fa-cart-shopping"></i></button>
                                        </form>


                                    </div>





                       
                                </div>
                            </div>
                        </swiper-slide>
                    }


                </swiper-container>
            }


        </div>


    </section>




</main>

@section Script{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js" integrity="sha512-3gJwYpMe3QewGELv8k/BX9vcqhryRdzRMxVfq6ngyWXwo03GFEzjsUm8Q7RZcHPHksttq7/GFoxjCVUjkjvPdw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/assets/js/Search.js"></script>
    @*  <script src="~/assets/js/JavaScript.js"></script>*@
    <script src="~/assets/js/shop.js"></script>

}